python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 0   --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 50  --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 100 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 150 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 200 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 250 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 300 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 350 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 400 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 450 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 500 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 550 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 600 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 650 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 700 --window 50
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 720 --window 50

python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 0   --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 50  --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 100 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 150 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 200 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 250 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 300 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 350 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 400 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 450 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 500 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 550 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 600 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 650 --window 100
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 670 --window 100

python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 0   --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 50  --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 100 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 150 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 200 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 250 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 300 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 350 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 400 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 450 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 500 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 550 --window 200
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 570 --window 200

python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 0   --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 50  --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 100 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 150 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 200 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 250 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 300 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 350 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 400 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 450 --window 300
python ./training/FcNN_SingleQubit_NewRawData_All_parameterized.py --start 470 --window 300
